"""
Guardian Eye — Live Stream Router (OPTIMIZED EDGE VERSION)
"""

import cv2
import asyncio
import json
import numpy as np
from typing import AsyncGenerator
from fastapi import APIRouter, WebSocket, WebSocketDisconnect
from fastapi.responses import StreamingResponse

from app.modules.pipeline import process_frame
from app.modules.thermal import rgb_to_thermal
from app.core.config import settings
from app.core.logger import get_logger

router = APIRouter()
logger = get_logger(__name__)

# Shared global state to prevent running the AI twice!
_last_annotated: np.ndarray = None
_last_thermal: np.ndarray = None
_last_result = None


def _open_camera() -> cv2.VideoCapture:
    # Check if it's a number (webcam index) or a string (IP cam / mp4 file)
    source = int(settings.VIDEO_SOURCE) if settings.VIDEO_SOURCE.isdigit() else settings.VIDEO_SOURCE
    cap = cv2.VideoCapture(source)
    cap.set(cv2.CAP_PROP_FPS, settings.STREAM_FPS)
    return cap


def _frame_to_jpeg(frame: np.ndarray) -> bytes:
    _, encoded = cv2.imencode(".jpg", frame, [cv2.IMWRITE_JPEG_QUALITY, 70])
    return encoded.tobytes()


async def _webcam_generator(mode: str = "annotated") -> AsyncGenerator[bytes, None]:
    global _last_annotated, _last_thermal, _last_result

    cap = _open_camera()
    if not cap.isOpened():
        placeholder = np.zeros((480, 640, 3), dtype=np.uint8)
        cv2.putText(placeholder, "NO CAMERA", (200, 240),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
        jpeg = _frame_to_jpeg(placeholder)
        while True:
            yield b"--frame\r\nContent-Type: image/jpeg\r\n\r\n" + jpeg + b"\r\n"
            await asyncio.sleep(0.1)
        return

    frame_idx = 0
    try:
        while True:
            await asyncio.sleep(0.001)

            ret, frame = cap.read()
            if not ret:
                break

            # 1. Resize for edge performance
            frame = cv2.resize(frame, (640, 480))

            # 2. Run master pipeline ONCE
            result = process_frame(
                frame=frame,
                frame_index=frame_idx,
                run_depth=False,
                job_id="live_stream",
            )
            _last_result = result

            # 3. Render visuals
            from app.modules.detection import detector
            detections = detector.detect(frame, use_tracking=True)

            pid_map = {
                d.track_id: p["person_id"]
                for p in result.persons
                for d in detections
                if d.track_id == p.get("track_id")
            }

            annotated = detector.annotate_frame(frame, detections, pid_map)

            from app.modules.environment import analyze_environment, annotate_env_frame
            env = analyze_environment(frame)
            annotated = annotate_env_frame(annotated, env)

            thermal, _ = rgb_to_thermal(frame, detections)

            output_frame = thermal if mode == "thermal" else annotated
            jpeg = _frame_to_jpeg(output_frame)

            yield b"--frame\r\nContent-Type: image/jpeg\r\n\r\n" + jpeg + b"\r\n"
            frame_idx += 1

    finally:
        cap.release()


@router.get("/webcam")
async def webcam_stream():
    return StreamingResponse(
        _webcam_generator(mode="annotated"),
        media_type="multipart/x-mixed-replace; boundary=frame"
    )


@router.get("/thermal")
async def thermal_stream():
    return StreamingResponse(
        _webcam_generator(mode="thermal"),
        media_type="multipart/x-mixed-replace; boundary=frame"
    )


# ── WebSocket (Now 100x Lighter) ─────────────────────────
@router.websocket("/ws")
async def websocket_stream(websocket: WebSocket):
    """
    WebSocket endpoint.
    It no longer runs the AI. It just broadcasts the _last_result
    generated by the webcam stream.
    """
    await websocket.accept()
    logger.info("WebSocket client connected")
    global _last_result

    try:
        while True:
            if _last_result is not None:
                payload = {
                    "frame_index": _last_result.frame_index,
                    "timestamp": _last_result.timestamp,
                    "person_count": _last_result.person_count,
                    "persons": _last_result.persons,
                    "environment": _last_result.environment,
                    "alerts": _last_result.alerts_fired,
                    "gps_lat": _last_result.gps_lat,
                    "gps_lon": _last_result.gps_lon,
                    "landing_zones": _last_result.landing_zones,
                }
                await websocket.send_text(json.dumps(payload))

            await asyncio.sleep(0.1)

    except WebSocketDisconnect:
        logger.info("WebSocket client disconnected")